### ISSUE TITLE
Minimize/Expand chat window functionality 

### ISSUE THREAD

**Issue by viddychang** [viddychang/covey.town#1]
This component will collapse or expand the chat window when clicked.

When minimized, the chat window will be collapsed into a "tab" which can be clicked on to expand the chat window. This is the default state: https://docs.google.com/presentation/d/1-riWCJp9oGj-NF-x6lAcq5mZKydMWIbkLbpvOkfb-N8/edit#slide=id.p

When expanded, the chat window will show the chats in the global chatroom with an option to minimize the chat window.

If a user goes through the following:

opens chat
selects user to chat with. now in private chat room
closes chat
re-opens chat
The private chat should show. In other words, whatever was the last state of the chat window should be what is shown given the same user session.

as of 3/18: in progress - 
```
In progress:

Using the react library: https://github.com/Wolox/react-chat-widget
```

**Comment by ankitamaps03** [comment]
This feature is ready for testing and code has been pushed to main branch. 

Can somebody please test this? @srutibalan  @navyak3011
