### ISSUE TITLE
Chat history for global chat 

### ISSUE THREAD

**Issue by viddychang** [viddychang/covey.town#5]
show the chats that were sent previously in the global chat

**Comment by ankitamaps03** [comment]
@viddychang : Does this have to be shown public town wise? (Every town should have a chat history?)

**Comment by viddychang** [comment]
@ankitamaps03 Hrm. The way I was thinking about this was that each town would have a chat history that are independent from other towns.

For example, I have towns *A* and *B*.

*A* has messages that were sent by users in that town. These *A* messages cannot be seen by users who are currently in town *B*.
